#release configuration
#Wed May 29 14:11:25 BST 2024
scm.commentPrefix=[maven-release-plugin] 
exec.pomFileName=pom.xml
pushChanges=true
releaseStrategyId=default
project.scm.net.openhft\:chronicle-analytics.url=scm\:git\:git@github.com\:OpenHFT/Chronicle-Analytics.git
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
remoteTagging=true
exec.additionalArguments=-P release -DskipTests -DaltReleaseDeploymentRepository\=chronicle-enterprise-release\:\:https\://nexus.chronicle.software/content/repositories/releases
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
projectVersionPolicyId=default
scm.url=scm\:git\:git@github.com\:OpenHFT/Chronicle-Analytics.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pinExternals=false
project.scm.net.openhft\:chronicle-analytics.connection=scm\:git\:git@github.com\:OpenHFT/Chronicle-Analytics.git
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.snapshotReleasePluginAllowed=false
exec.activateProfiles=release-sign-artifacts,gpg-properties,sign-artifact,guarded,checksum-policy-fail,obfuscation,release
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.scm.net.openhft\:chronicle-analytics.developerConnection=scm\:git\:git@github.com\:OpenHFT/Chronicle-Analytics.git
project.scm.net.openhft\:chronicle-analytics.tag=master
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
completedPhase=scm-check-modifications
